---
title: "Final Porject"
author: "Dongzhou Huang"
date: "04/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
set.seed(1234)
n =50000
idnum = 12
dnum = 12
  numnormal <- floor(idnum/2 )
  numcategory <- floor(idnum/6)
  numbernoulli <- floor(idnum/3)
  numuniform <- floor(idnum/6)
  x1 <- matrix(rnorm(n * numnormal, mean = 0, sd=1), ncol = n )
  x2 <- sample(x=c(1,2,3,4,5), 
              size=n, replace=TRUE, prob=c(0.1,0.3, 0.2, 0.05, 0.35))
  x3 <- sample(x=c(1,2,3), 
              size=n, replace=TRUE, prob=c(1/3, 1/3,1/3))
  A <- matrix(rep(0, n*numbernoulli), ncol = n)
  for(i in 1:numbernoulli)
  {
    p <- runif(1, min = 0, max = 1)
    A[i,] <- sample(x=c(0,1), size = n, replace = TRUE, prob = c(1-p, p))
  }
x4 <- runif(n, min = 0, max = 1)
x5 <- runif(n, min=1, max = 10)
c <- c(rep(1:6), 0.2, 0.3, c(-0.5,1,1.5,-2), 1, 0.1)
xb <- apply(x1, 2, sum) + 0.2 * x2 + 0.3 *x3 - 0.5*A[1,] + A[2,]+ 1.5*A[3,] - 2 *A[4,] + x4 + 0.1*x5 -2
p <- 1/(1 + exp(-xb))
y <- rbinom(n = n, size = 1, prob = p)
z1 <- matrix(rnorm(n * 7, mean = 0, sd=1), ncol = n )
z2 <- sample(x=c(1,2,3,4,5), 
              size=n, replace=TRUE, prob=rep(1/5,5))
z3 <- sample(x=c(1,2,3,4,5,6,7,8,9,10), 
              size=n, replace=TRUE, prob=c(rep(1/20,5), rep(3/20,5)))
 B <- matrix(rep(0, n*5), ncol = n)
for(i in 1:5)
  {
    k <- (runif(1, min = 0, max = 1)+1)/2
    B[i,] <- sample(x=c(0,1), size = n, replace = TRUE, prob = c(1-k, k))
}
z4 <- rpois(n, lambda = 5)
z5 <- rpois(n, lambda = 10)
z6 <- runif(n, min = 1, max =10)
data_logisric <- data.frame("y" = y, "x1" = x1[1,], "x2" = x1[2,], "x3" = x1[3,], "x4" = x1[4,], "x5" = x1[5,], "x6" = x1[6,], "x7" = x2, "x8" = x3, "x9" = A[1,], "x10"  = A[2,], "x11" = A[3,], "x12" = A[4,], "x13" = x4, "x14" = x5, "z1" = z1[1,], "z2" = z1[2,], "z3" = z1[3,], "z4" = z1[4,], "z5" = z1[5,], "z6" = z1[6,], "z7" = z1[7,], "z8" = z2, "z9" = z3, "z10" = B[1,], "z11" = B[2,], "z12" = B[3,], "z13" = B[4,], "z14" = B[5,], "z15" = z4, "z16" = z5, "z17" = z6) 
#write.csv(data_logisric, "D:\\course\\SML\\final_project\\LogisticData.csv", row.names = FALSE)
```

```{r, echo=FALSE}
#logistic_model <- glm(y ~ ., family = "binomial", data = data_logisric) %>%
#  stepAIC(trace = FALSE)
#summary(logistic_model)
```

```{r, echo=FALSE}
set.seed(1234)
n =50000
idnum = 12
dnum = 12
  numnormal <- floor(idnum/2 )
  numcategory <- floor(idnum/6)
  numbernoulli <- floor(idnum/3)
  numuniform <- floor(idnum/6)
  x1 <- matrix(rnorm(n * numnormal, mean = 0, sd=1), ncol = n )
  x2 <- sample(x=c(1,2,3,4,5), 
              size=n, replace=TRUE, prob=c(0.1,0.3, 0.2, 0.05, 0.35))
  x3 <- sample(x=c(1,2,3), 
              size=n, replace=TRUE, prob=c(1/3, 1/3,1/3))
  A <- matrix(rep(0, n*numbernoulli), ncol = n)
  for(i in 1:numbernoulli)
  {
    p <- runif(1, min = 0, max = 1)
    A[i,] <- sample(x=c(0,1), size = n, replace = TRUE, prob = c(1-p, p))
  }
x4 <- runif(n, min = 0, max = 1)
x5 <- runif(n, min=1, max = 10)
c <- c(rep(1:6), 0.2, 0.3, c(-0.5,1,1.5,-2), 1, 0.1)
xb <- apply(x1, 2, sum) + 0.2 * x2 + 0.3 *x3 - 0.5*A[1,] + A[2,]+ 1.5*A[3,] - 2 *A[4,] + x4 + 0.1*x5 -2
p <- 1/(1 + exp(-xb))
y <- rbinom(n = n, size = 1, prob = p)
z1 <- matrix(rnorm(n * 7, mean = 0, sd=1), ncol = n )
z2 <- sample(x=c(1,2,3,4,5), 
              size=n, replace=TRUE, prob=rep(1/5,5))
z3 <- sample(x=c(1,2,3,4,5,6,7,8,9,10), 
              size=n, replace=TRUE, prob=c(rep(1/20,5), rep(3/20,5)))
 B <- matrix(rep(0, n*5), ncol = n)
for(i in 1:5)
  {
    k <- (runif(1, min = 0, max = 1)+1)/2
    B[i,] <- sample(x=c(0,1), size = n, replace = TRUE, prob = c(1-k, k))
}
z4 <- rpois(n, lambda = 5)
z5 <- rpois(n, lambda = 10)
z6 <- runif(n, min = 1, max =10)
data_logisric <- data.frame("y" = y, "x1" = x1[1,], "x2" = x1[2,], "x3" = x1[3,], "x4" = x1[4,], "x5" = x1[5,], "x6" = x1[6,], "x7" = x2, "x8" = x3, "x9" = A[1,], "x10"  = A[2,], "x11" = A[3,], "x12" = A[4,], "x13" = x4, "x14" = x5, "z1" = z1[1,], "z2" = z1[2,], "z3" = z1[3,], "z4" = z1[4,], "z5" = z1[5,], "z6" = z1[6,], "z7" = z1[7,], "z8" = z2, "z9" = z3, "z10" = B[1,], "z11" = B[2,], "z12" = B[3,], "z13" = B[4,], "z14" = B[5,], "z15" = z4, "z16" = z5, "z17" = z6) 
#write.csv(data_logisric, "D:\\course\\SML\\final_project\\LogisticData.csv", row.names = FALSE)
p1 <- atan(xb)/pi/2 + 1/2
y1 <- rbinom(n = n, size = 1, prob = p1)
data_linear <- data.frame("y" = y1, "x1" = x1[1,], "x2" = x1[2,], "x3" = x1[3,], "x4" = x1[4,], "x5" = x1[5,], "x6" = x1[6,], "x7" = x2, "x8" = x3, "x9" = A[1,], "x10"  = A[2,], "x11" = A[3,], "x12" = A[4,], "x13" = x4, "x14" = x5, "z1" = z1[1,], "z2" = z1[2,], "z3" = z1[3,], "z4" = z1[4,], "z5" = z1[5,], "z6" = z1[6,], "z7" = z1[7,], "z8" = z2, "z9" = z3, "z10" = B[1,], "z11" = B[2,], "z12" = B[3,], "z13" = B[4,], "z14" = B[5,], "z15" = z4, "z16" = z5, "z17" = z6)
write.csv(data_linear, "D:\\course\\SML\\final_project\\LinearData.csv", row.names = FALSE)
```

```{r, echo=FALSE}
set.seed(1234)
n =50000
x1 <- runif(n, min = 1, max = 10)
x2 <- sample(x=c(0,1), size = n, replace = TRUE, prob = c(0.5, 0.5))
xb <- 0.5 * x1 + 1 * x2 - 2
p <- 1/(1 + exp(-xb))
y <- rbinom(n = n, size = 1, prob = p)
z1 <- rnorm(n, mean = 1, sd=1)
z2 <- rpois(n, lambda=5)
z3 <- sample(x=c(0,1), size = n, replace = TRUE, prob = c(0.3, 0.7))
data_logisric <- data.frame("y" = y, "x1" = x1, "x2" = x2, "z1"=z1, "z2" = z2, "z3"= z3)
write.csv(data_logisric, "D:\\course\\SML\\final_project\\LogisticData_lessvaraible.csv",
          row.names = FALSE)
p1 <- atan(xb)/pi/2 + 1/2
y1 <- rbinom(n = n, size = 1, prob = p1)
data_linear <- data.frame("y" = y1, "x1" = x1, "x2" = x2, "z1"=z1, "z2" = z2, "z3"= z3)
#write.csv(data_linear, "D:\\course\\SML\\final_project\\LinearData_lessvaraible.csv",
#          row.names = FALSE)
sum(abs(y-y1))
```

```{r, echo=FALSE}
logistic_model <- glm(y ~ ., family = "binomial", data = data_logisric)
summary(logistic_model)
```